import type { Metadata } from "next";
import { Toaster } from 'sonner';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Memory Card Game",
  description: "Generated by BrendoLee",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster
          position="top-center"
          // toastOptions={{
          //   style: {
          //     padding: "12px 20px", // Ajuste o padding conforme necessário
          //     fontSize: "16px", // Ajuste o tamanho da fonte
          //     background: "#4F46E5", // Cor do fundo do toast
          //     color: "#FFFFFF", // Cor do texto
          //     borderRadius: "8px", // Arredondar os cantos
          //   },
          // }}
        />
      </body>
    </html>
  );
}
